#%RAML 1.0 DataType

type: object
displayName: salary
properties:
  salary_id:
    type: number
  company_name:
    type: string
  start_date:
    type: datetime-only
  end_date:
    type: datetime-only
  number_of_Hours:
    type: number
  hourly_rate:
    type: number
  gross_amount:
    type: number
  net_pay:
    type: number
  reimbursement:
    type: number
